In [40]:
import numpy as np
import pandas as pd
from numpy.linalg import inv
import matplotlib.pyplot as plt
%matplotlib inline

In [8]:
jacobian_data = pd.read_csv('jacobian_finite_differenced.dat', sep=' ', header=None)

Fill the jacobian with the raw data.

In [38]:
jacobian = np.zeros((8,8))

for i in range(0,len(jacobian_data)):
    row = jacobian_data.icol(0)
    col = jacobian_data.icol(1)
    data = jacobian_data.icol(2)
    
    jacobian[row[i], col[i]] = data[i]

In [30]:
jacobian_data.icol(0).irow(63)

7

In [39]:
jacobian

array([[ -3.21118000e+03,   2.29000000e-04,   0.00000000e+00,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   0.00000000e+00],
       [  1.23581000e+05,   7.90000000e-05,   0.00000000e+00,
         -8.00000000e-06,  -1.03279000e+02,  -1.50000000e-05,
         -1.03279000e+02,  -8.00000000e-06],
       [  0.00000000e+00,   0.00000000e+00,  -3.21118000e+03,
          2.29000000e-04,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   0.00000000e+00],
       [  0.00000000e+00,  -8.00000000e-06,   1.23581000e+05,
          7.90000000e-05,  -1.03279000e+02,  -8.00000000e-06,
         -1.03279000e+02,  -1.50000000e-05],
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00,  -3.21118000e+03,   2.29000000e-04,
          0.00000000e+00,   0.00000000e+00],
       [  0.00000000e+00,  -1.50000000e-05,   0.00000000e+00,
         -7.00000000e-06,   1.23788000e+05,   7.90000000e-05,
          0.00000000e+00,  -8.0

Even rows refer to liquid saturation variable, and odd rows are the gas pressure.

In [65]:
residual = np.zeros(8)
residual[0] = -21.8046;
residual[2] = -21.8046;
residual[4] = 21.8046;
residual[6] = 21.8046;

In [68]:
sol=np.linalg.solve(jacobian, residual)
sol

array([  7.15455990e-05,  -9.42133371e+04,   7.15455990e-05,
        -9.42133371e+04,  -7.07871159e-05,   9.42239731e+04,
        -7.07871159e-05,   9.42239731e+04])

In [67]:
np.dot(jacobian, sol)

array([ -2.18046000e+01,   1.77635684e-15,  -2.18046000e+01,
         1.77635684e-15,   2.18046000e+01,   1.77635684e-15,
         2.18046000e+01,   0.00000000e+00])

In [70]:
sol[0]=0
sol[2]=0
sol[4]=0
sol[6]=0
sol

array([     0.        , -94213.33713259,      0.        , -94213.33713259,
            0.        ,  94223.97305304,      0.        ,  94223.97305304])

In [71]:
np.dot(jacobian, sol)

array([-21.5748542 ,  -8.85629832, -21.5748542 ,  -8.85629832,
        21.57728983,   8.7625955 ,  21.57728983,   8.7625955 ])